<?php

declare(strict_types=1);

namespace Drupal\ai_provider_universal\Plugin\AiGuardrail;

use Drupal\Component\Plugin\ConfigurableInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Plugin\PluginFormInterface;
use Drupal\Core\StringTranslation\StringTranslationTrait;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\ai\Attribute\AiGuardrail;
use Drupal\ai\Guardrail\AiGuardrailPluginBase;
use Drupal\ai\Guardrail\Result\GuardrailResultInterface;
use Drupal\ai\Guardrail\Result\PassResult;
use Drupal\ai\Guardrail\Result\RewriteOutputResult;
use Drupal\ai\OperationType\Chat\ChatMessage;
use Drupal\ai\OperationType\Chat\ChatOutput;
use Drupal\ai\OperationType\Chat\StreamedChatMessageIteratorInterface;
use Drupal\ai\OperationType\InputInterface;
use Drupal\ai\OperationType\OutputInterface;

/**
 * Appends a visible AI disclosure to chat responses (post-generate).
 *
 * Helper for AI Act Art. 50(1)-style interaction disclosure: add this plugin
 * to a Guardrail set's post-generate step and every non-streamed response
 * carries the configured suffix. Streamed responses pass through untouched —
 * disclose in the chat UI instead for those.
 */
#[AiGuardrail(
  id: 'universal_disclosure_suffix',
  label: new TranslatableMarkup('AI disclosure suffix (Universal)'),
  description: new TranslatableMarkup('Appends a configurable disclosure text to every chat response.'),
)]
class DisclosureSuffix extends AiGuardrailPluginBase implements ConfigurableInterface, PluginFormInterface {

  use StringTranslationTrait;

  /**
   * {@inheritdoc}
   */
  public function processInput(InputInterface $input): GuardrailResultInterface {
    return new PassResult('Suffix guardrails only act on output.', $this);
  }

  /**
   * {@inheritdoc}
   */
  public function processOutput(OutputInterface $output): GuardrailResultInterface {
    if (!$output instanceof ChatOutput) {
      return new PassResult('Output is not a chat output, skipping suffix.', $this);
    }
    $normalized = $output->getNormalized();
    if ($normalized instanceof StreamedChatMessageIteratorInterface) {
      return new PassResult('Streamed output is not suffixed; disclose in the UI.', $this);
    }
    if (!$normalized instanceof ChatMessage) {
      return new PassResult('No text message found in output.', $this);
    }

    $suffix = trim((string) ($this->configuration['suffix_text'] ?? ''));
    if ($suffix === '') {
      return new PassResult('No suffix configured.', $this);
    }
    $text = $normalized->getText();
    if ($text === '' || str_contains($text, $suffix)) {
      // Empty answers (e.g. pure tool calls) and already-suffixed text
      // (escalation re-runs the post set on the retried answer) are left
      // alone so the disclosure never doubles up.
      return new PassResult('Nothing to suffix.', $this);
    }

    return new RewriteOutputResult($text . $this->separator() . $suffix, $this);
  }

  /**
   * String placed between the original text and the suffix.
   */
  protected function separator(): string {
    return "\n\n";
  }

  /**
   * Default text for the suffix form element and empty configuration.
   */
  protected function defaultSuffixText(): string {
    return (string) $this->t('This response was generated by an AI system.');
  }

  /**
   * {@inheritdoc}
   */
  public function getConfiguration(): array {
    return $this->configuration;
  }

  /**
   * {@inheritdoc}
   */
  public function setConfiguration(array $configuration): void {
    $this->configuration = $configuration;
  }

  /**
   * {@inheritdoc}
   */
  public function defaultConfiguration(): array {
    return ['suffix_text' => $this->defaultSuffixText()];
  }

  /**
   * {@inheritdoc}
   */
  public function buildConfigurationForm(array $form, FormStateInterface $form_state): array {
    $form['suffix_text'] = [
      '#type' => 'textarea',
      '#title' => $this->t('Suffix text'),
      '#default_value' => $this->configuration['suffix_text'] ?? $this->defaultSuffixText(),
      '#description' => $this->t('Appended after the response, separated by a blank line. Leave empty to disable.'),
    ];
    return $form;
  }

  /**
   * {@inheritdoc}
   */
  public function validateConfigurationForm(array &$form, FormStateInterface $form_state): void {
  }

  /**
   * {@inheritdoc}
   */
  public function submitConfigurationForm(array &$form, FormStateInterface $form_state): void {
    $this->setConfiguration([
      'suffix_text' => (string) $form_state->getValue('suffix_text', ''),
    ]);
  }

}
