<?php

declare(strict_types=1);

namespace Drupal\ai_provider_universal_governance\Hook;

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Hook\Attribute\Hook;
use Drupal\Core\StringTranslation\StringTranslationTrait;
use Drupal\node\NodeInterface;

/**
 * Hook implementations for ai_provider_universal_governance.
 */
class AiProviderUniversalGovernanceHooks {

  use StringTranslationTrait;

  /**
   * Implements hook_node_view().
   *
   * Render marking for AI-origin content (Art. 50(2)/(4) style), driven by
   * the fields shipped in the ai_content_disclosure recipe. On the node's
   * canonical page ("full" view mode; teasers and feeds are not the
   * canonical exposure):
   *
   * - machine-readable <meta name="ai-origin"> when field_ai_origin is
   *   generated/assisted, except for an assistive_edit exemption (50(2):
   *   marking does not apply);
   * - a visible label at first exposure when field_ai_disclosure_req is on
   *   and no exemption clears it: editorial_responsibility drops the label,
   *   artistic_creative_satirical swaps the banner for an adapted credits
   *   line at the bottom (50(4): adapted, not removed).
   *
   * Nodes without these fields are untouched. ECA/Workflow may restyle or
   * replace the label; this hook guarantees the default.
   */
  #[Hook('node_view')]
  public function nodeView(array &$build, NodeInterface $node, EntityViewDisplayInterface $display, string $view_mode): void {
    if ($view_mode !== 'full' || !$node->hasField('field_ai_origin')) {
      return;
    }
    $origin = (string) ($node->get('field_ai_origin')->value ?? '');
    if (!in_array($origin, ['generated', 'assisted'], TRUE)) {
      return;
    }
    $exemption = $node->hasField('field_ai_exemption')
      ? (string) ($node->get('field_ai_exemption')->value ?? '')
      : '';
    if ($exemption === 'assistive_edit') {
      return;
    }

    // IPTC digital source type, same vocabulary as the AiOriginMarker
    // Guardrail plugin.
    $source_type = $origin === 'generated'
      ? 'trainedAlgorithmicMedia'
      : 'compositeWithTrainedAlgorithmicMedia';
    $build['#attached']['html_head'][] = [
      [
        '#tag' => 'meta',
        '#attributes' => [
          'name' => 'ai-origin',
          'content' => $origin . '; digitalSourceType=' . $source_type,
        ],
      ],
      'ai_provider_universal_governance_origin',
    ];

    $required = $node->hasField('field_ai_disclosure_req')
      && (bool) $node->get('field_ai_disclosure_req')->value;
    if (!$required || $exemption === 'editorial_responsibility') {
      return;
    }

    if ($exemption === 'artistic_creative_satirical') {
      $text = $this->t('Created with the use of artificial intelligence.');
      $weight = 100;
      $class = 'ai-disclosure-credits';
    }
    else {
      $text = $origin === 'generated'
        ? $this->t('This content was generated by artificial intelligence.')
        : $this->t('This content was created with the assistance of artificial intelligence.');
      $weight = -100;
      $class = 'ai-disclosure-label';
    }
    $build['ai_disclosure_label'] = [
      '#type' => 'html_tag',
      '#tag' => 'p',
      '#attributes' => ['class' => [$class]],
      '#value' => $text,
      '#weight' => $weight,
    ];
  }

}
